### ISSUE TITLE
{ error: 'rapid bases error 2' }

### ISSUE THREAD

**Issue by Tej5** [QBisConsult/psql-api#3]
While trying to connect to api I can configure but can't save or acess any tab on api.

I see this 

RAPID database connection - OK

RAPID read config - OK

RAPID bases config 0 - OK

RAPID SQLS - OK

{ error: 'rapid bases error 2' }

**Comment by adipatrascu** [comment]
The server will create a database structure meta-data used next to it's API services validation,
the error message 'rapid bases error 2' is triggered at this moment.
Please check your database structure, and add more details. (js/db_struct.js  line 10) it looks like it can not read the structure from the database server.
